// riddleConfig.js

export const RIDDLES = [
  { id: 1,  text: "The head of this mansion stands tall, yet meek, the portrait on the... is what you must seek.", bookshelfId: "shelf01" },
  { id: 2,  text: "The world is bigger than you can imagine, however on the... it's quite small in this mansion.", bookshelfId: "shelf02" },
  { id: 3,  text: "Dusty and unkept, the... needs to be cleaned and swept.", bookshelfId: "shelf03" },
  { id: 4,  text: "Cold, yet small, a tiny town is on the... of this hall.", bookshelfId: "shelf04" },
  { id: 5,  text: "Should you seek news of old yesteryear, on the... it's waiting here.", bookshelfId: "shelf05" },
  { id: 6,  text: "Packed full of playthings, the... looks fun, yet frightening", bookshelfId: "shelf06" },
  { id: 7,  text: "The... is dutifully guarded, but fear not for his shift hasn't started.", bookshelfId: "shelf07" },
  { id: 8,  text: "On the... is something round among its angles, any sharp touch will leave it mangled.", bookshelfId: "shelf08" },
  { id: 9,  text: "Eyes wide open, and wings spread wider, the... is what you desire.", bookshelfId: "shelf09" },
  { id: 10, text: "Is it empty, or full of air? The... may have answers there.", bookshelfId: "shelf10" },
  { id: 11, text: "You shan't lose track of time, while browsing... binds.", bookshelfId: "shelf11" },
  { id: 12, text: "Beauty doesn't last forever, decaying in a vase, the... is where it is placed.", bookshelfId: "shelf12" },
  { id: 13, text: "Like a soothing melody, the photo on the... may be your remedy.", bookshelfId: "shelf13" },
  { id: 14, text: "The cold stare of the mansion's Lady, make the... feel rather shady.", bookshelfId: "shelf14" },
  { id: 15, text: "A child, innocent and pure, looks down from the... with a face quite demure.", bookshelfId: "shelf15" },
  { id: 16, text: "Tall when its young and short when its old, the... is a riddle often told.", bookshelfId: "shelf16" },
  { id: 17, text: "Adding fuel to the fire, the... is what you desire.", bookshelfId: "shelf17" },
  { id: 18, text: "Its preferable to go up it rather than under, as the... can be a bit of a blunder.", bookshelfId: "shelf18" },
  { id: 19, text: "Right side up or up-side down? The... looks turned around", bookshelfId: "shelf19" },
  { id: 20, text: "A gift awaits on the... but not for you and instead someone else.", bookshelfId: "shelf20" },
  { id: 21, text: "Water can run, but also hide, within the structure of the... side.", bookshelfId: "shelf21" },
  { id: 22, text: "Lying in pieces, a scene of destruction, the... poses a bit of an obstruction.", bookshelfId: "shelf22" },
  { id: 23, text: "The... offers a home for your jacket, but will stay empty if you lack it.", bookshelfId: "shelf23" },
  { id: 24, text: "Mysteriously decorated, lavishly without lace, something's amiss about the...", bookshelfId: "shelf24" },
  { id: 25, text: "On the... there lie the tools, used to write unrequited love, like a fool.", bookshelfId: "shelf25" },
  { id: 26, text: "A friend sleeps on the... be careful not to disturb the peaceful look on their face.", bookshelfId: "shelf26" },
  { id: 27, text: "Here lies stories, some written in stone, on the... at least they aren't alone.", bookshelfId: "shelf27" },
  { id: 28, text: "The... will give you a moment of self-reflection, or self-affection, if that is your intention.", bookshelfId: "shelf28" }
];
